# Model param
dataset:
  sh_degree : 3
  source_path : "/home/gaussian-grouping/data/lerf_mask/ramen" #dataset path
  model_path : "/home/lang-grouping/output/lerf_mask/ramen" #output path
  language_features_name : "language_features_dim3" # compressed lang feature name
  images : "images"
  resolution : -1
  white_background : False
  feature_level : 1
  data_device : "cuda"
  eval : False
  object_path : "object_mask"
  num_classes : 256
  n_views : 100 
  random_init : False
  train_split : False

# Pipeline param
pipe:
  convert_SHs_python : False
  compute_cov3D_python : False
  debug : False

#Optim param
opt:
  iterations : 30_000
  position_lr_init : 0.00016
  position_lr_final : 0.0000016
  position_lr_delay_mult : 0.01
  position_lr_max_steps : 30_000
  feature_lr : 0.0025
  opacity_lr : 0.05
  scaling_lr : 0.005
  language_feature_lr : 0.0025 #
  object_lr : 0.0005
  include_lang_feature : False #
  rotation_lr : 0.001
  percent_dense : 0.01
  lambda_dssim : 0.2
  densification_interval : 100
  opacity_reset_interval : 3000 
  densify_from_iter : 500
  densify_until_iter : 15_000 
  densify_grad_threshold : 0.0002
  
  #grouping param
  reg3d_interval : 2
  reg3d_k : 5
  reg3d_lambda_val : 2
  reg3d_max_points : 300000
  reg3d_sample_size : 1000

#User loccally option
ip : 127.0.0.1
port: 6011
debug_from : -1
detect_anomaly: False
test_iterations : [7_000, 30_000]
save_iterations : [7_000, 30_000]
quiet : False
checkpoint_iterations : [7_000, 30_000]
start_checkpoint : False


# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~

