# Model param
dataset:
  sh_degree : 3
  source_path : "/home/gaussian-grouping/data/lerf_mask/figurines" #dataset path
  model_path : "/home/lang-grouping/output/lerf_mask/figurines_1view_contrastive" #output path
  language_features_name : "language_features_dim3" # compressed lang feature name
  images : "images"
  resolution : -1
  white_background : False
  feature_level : 1
  data_device : "cuda"
  eval : False
  lf_path : ''
  object_path : "object_mask"
  num_classes : 256
  n_views : 100 
  random_init : False
  train_split : False

# Pipeline param
pipe:
  convert_SHs_python : False
  compute_cov3D_python : False
  debug : False

#Optim param
opt:
  include_lang_feature : True #
  iterations : 30_000
  position_lr_init : 0.00016
  position_lr_final : 0.0000016
  position_lr_delay_mult : 0.01
  position_lr_max_steps : 30_000
  feature_lr : 0.0025
  opacity_lr : 0.05
  scaling_lr : 0.005
  language_feature_lr : 0.0025 #
  object_lr : 0.0025 # 
  rotation_lr : 0.001
  percent_dense : 0.01
  lambda_dssim : 0.2
  densification_interval : 100
  opacity_reset_interval : 3000 
  densify_from_iter : 500
  densify_until_iter : 15_000 
  densify_grad_threshold : 0.0002
  
  #contrastive learning param
  contrastive:
    interval : 2
    k : 5
    lambda_val : 2

#User loccally option
ip : 127.0.0.1
port: 6012
debug_from : -1
detect_anomaly: False
test_iterations : [30_000]
save_iterations : [30_000]
quiet : False
use_wandb : True
checkpoint_iterations : [30_000]
start_checkpoint : 30000 # 30000 when language distil


# No need to change
hydra:
  run: # singlue run mode. multi run 하고 싶으면 sweep키워드 사용
    dir: ${dataset.model_path}_1 # output directory 
  output_subdir: ~
#output subdir : .hydra 폴더의 이름을 바꿀 수 있음 ~는 안만들겠다는 뜻
