#eval param
dataset_name: "teatime"
feat_dir: "/home/splat/lang-grouping/lang-grouping/output/lerf_mask/${dataset_name}"     
ae_ckpt_dir: "/home/splat/lang-grouping/lang-grouping/autoencoder/ckpt/lerf_mask"
output_dir: "/home/splat/lang-grouping/lang-grouping/eval_result/${dataset_name}"
json_folder: "/home/splat/lang-grouping/lang-grouping/data/lerf_ovs/label"
mask_thresh: 0.4



encoder_dims: [256, 128, 64, 32, 3]
decoder_dims: [16, 32, 64, 128, 256, 256, 512]

# No need to change
hydra:
  run:
    dir: .
  output_subdir: null

