#eval param
dataset_name: "teatime"
feat_dir: "/root/shan/lang_grouping/output/teatime"
ae_ckpt_dir: "/root/shan/lang_grouping/autoencoder/ckpt"
output_dir: "/root/shan/lang_grouping/eval_result/langsplat_baseline"
json_folder: "/root/shan/lang_grouping/dataset/lerf_ovs/label"
mask_thresh: 0.4

encoder_dims: [256, 128, 64, 32, 3]
decoder_dims: [16, 32, 64, 128, 256, 256, 512]

# No need to change
hydra:
  run:
    dir: .
  output_subdir: null

