#eval param
dataset_name: "figurines"
feat_dir: "/home/splat/lang-grouping/lang-grouping/output/lerf_mask/figurines_1view_contrastive_withdense"     
ae_ckpt_dir: "/home/splat/lang-grouping/lang-grouping/autoencoder/ckpt/lerf_mask"
output_dir: "/home/splat/lang-grouping/lang-grouping/eval_result/1view_contrastive_withdense"
json_folder: "/home/splat/lang-grouping/lang-grouping/data/lerf_ovs/label"
mask_thresh: 0.4



encoder_dims: [256, 128, 64, 32, 3]
decoder_dims: [16, 32, 64, 128, 256, 256, 512]

# No need to change
hydra:
  run:
    dir: .
  output_subdir: null

