#eval param
dataset_name: "figurines"
feat_dir: "/home/gaussian-grouping/lang-grouping/output/lerf_mask/figurines_2view_contrastive"
ae_ckpt_dir: "/home/gaussian-grouping/lang-grouping/autoencoder/ckpt/lerf_mask"
output_dir: "/home/gaussian-grouping/lang-grouping/eval_result/contrastive2view"
json_folder: "/home/gaussian-grouping/data/lerf_ovs/label"
mask_thresh: 0.4

encoder_dims: [256, 128, 64, 32, 3]
decoder_dims: [16, 32, 64, 128, 256, 256, 512]

# No need to change
hydra:
  run:
    dir: .
  output_subdir: null

